# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  reverse_proxy:    
    labels:
      - traefik.http.routers.traefik.middlewares[1]=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_HTPASSWD}

  frontend:
    labels:
      - traefik.http.routers.frontend.middlewares[1]=frontend-auth
      - traefik.http.middlewares.frontend-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_HTPASSWD}
